### ISSUE TITLE
Error Running Examples?

### ISSUE THREAD

**Issue by DOLLCAT-Hub** [xinjli/transphone#2]
I tried installing transphone both using pip and from source, and I keep getting the following error:
**>>> from transphone.g2p import read_g2p
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/osboxes/Desktop/transphone-main/transphone/g2p.py", line 2, in <module>
    from transphone.model.transformer import TransformerG2P
  File "/home/osboxes/Desktop/transphone-main/transphone/model/transformer.py", line 6, in <module>
    from transphone.data.utils import pad_sos_eos
ModuleNotFoundError: No module named 'transphone.data'**

Thank you very much!

**Comment by xinjli** [comment]
Hi, thanks for letting me know.

I ignored the data dir in the repo, can you try pulling from github again and rerun?

**Comment by DOLLCAT-Hub** [comment]
Sorry I was away from my computer. It works after the fix. Thank you!
